function surf2stl(filename, x, y, z, mode)

%SURF2STL  Write a surface (as X, Y, Z grid data) to an STL file.
%
%   surf2stl(FILENAME, X, Y, Z) writes a binary STL file.
%   surf2stl(FILENAME, X, Y, Z, MODE) additionally lets you choose the
%   output mode: 'binary' (default) or 'ascii'.
%
%   X, Y, Z are matrices of the same size, as produced by MESHGRID or
%   NDGRID, describing a surface on a rectangular grid. Two triangular
%   facets are created for every grid cell; cells touching a NaN in any
%   of their four corners are skipped.
%
%   Used by processScanDistance.m to export the final scanned mesh.

    if nargin < 5
        mode = 'binary';
    end

    if ~isequal(size(x), size(y), size(z))
        error('surf2stl:sizeMismatch', 'X, Y and Z must be the same size.');
    end

    [rows, cols] = size(z);

    facets = buildFacets(x, y, z, rows, cols);

    switch lower(mode)
        case 'binary'
            writeBinarySTL(filename, facets);
        case 'ascii'
            writeAsciiSTL(filename, facets);
        otherwise
            error('surf2stl:badMode', 'MODE must be ''binary'' or ''ascii''.');
    end
end

% =========================================================================
function facets = buildFacets(x, y, z, rows, cols)
% Build a list of triangle facets (with normals) from the grid,
% skipping any grid cell that touches a NaN vertex.

    maxFacets = 2 * (rows - 1) * (cols - 1);
    facets = struct('normal', cell(maxFacets, 1), 'v1', [], 'v2', [], 'v3', []);

    count = 0;
    for i = 1:rows-1
        for j = 1:cols-1
            % Four corners of this grid cell
            p1 = [x(i,   j),   y(i,   j),   z(i,   j)  ];
            p2 = [x(i,   j+1), y(i,   j+1), z(i,   j+1)];
            p3 = [x(i+1, j+1), y(i+1, j+1), z(i+1, j+1)];
            p4 = [x(i+1, j),   y(i+1, j),   z(i+1, j)  ];

            if any(isnan([p1 p2 p3 p4]))
                continue; % skip cells with missing data
            end

            % First triangle: p1 -> p2 -> p3
            count = count + 1;
            facets(count).v1 = p1;
            facets(count).v2 = p2;
            facets(count).v3 = p3;
            facets(count).normal = triangleNormal(p1, p2, p3);

            % Second triangle: p1 -> p3 -> p4
            count = count + 1;
            facets(count).v1 = p1;
            facets(count).v2 = p3;
            facets(count).v3 = p4;
            facets(count).normal = triangleNormal(p1, p3, p4);
        end
    end

    facets = facets(1:count);
end

% =========================================================================
function n = triangleNormal(p1, p2, p3)
% Unit normal for a triangle, via cross product of two edge vectors.

    u = p2 - p1;
    v = p3 - p1;
    n = cross(u, v);

    len = norm(n);
    if len > eps
        n = n / len;
    else
        n = [0 0 0]; % degenerate triangle
    end
end

% =========================================================================
function writeAsciiSTL(filename, facets)
    fid = fopen(filename, 'w');
    if fid == -1
        error('surf2stl:fileOpen', 'Could not open %s for writing.', filename);
    end

    [~, solidName] = fileparts(filename);
    fprintf(fid, 'solid %s\n', solidName);

    for k = 1:numel(facets)
        f = facets(k);
        fprintf(fid, '  facet normal %e %e %e\n', f.normal(1), f.normal(2), f.normal(3));
        fprintf(fid, '    outer loop\n');
        fprintf(fid, '      vertex %e %e %e\n', f.v1(1), f.v1(2), f.v1(3));
        fprintf(fid, '      vertex %e %e %e\n', f.v2(1), f.v2(2), f.v2(3));
        fprintf(fid, '      vertex %e %e %e\n', f.v3(1), f.v3(2), f.v3(3));
        fprintf(fid, '    endloop\n');
        fprintf(fid, '  endfacet\n');
    end

    fprintf(fid, 'endsolid %s\n', solidName);
    fclose(fid);
end

% =========================================================================
function writeBinarySTL(filename, facets)
    fid = fopen(filename, 'w');
    if fid == -1
        error('surf2stl:fileOpen', 'Could not open %s for writing.', filename);
    end

    % 80-byte header (unused, but required by the format)
    header = zeros(1, 80, 'uint8');
    headerText = uint8('Binary STL generated by surf2stl.m');
    header(1:numel(headerText)) = headerText;
    fwrite(fid, header, 'uint8');

    % Number of triangles
    fwrite(fid, numel(facets), 'uint32');

    for k = 1:numel(facets)
        f = facets(k);
        fwrite(fid, single(f.normal), 'float32');
        fwrite(fid, single(f.v1), 'float32');
        fwrite(fid, single(f.v2), 'float32');
        fwrite(fid, single(f.v3), 'float32');
        fwrite(fid, uint16(0), 'uint16'); % attribute byte count
    end

    fclose(fid);
end
